- name: Get local-ipv4-address from dc
  ansible.windows.win_uri:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    return_content: true
  delegate_to: windows_dc
  register: content
  
- name: print ipv4 address
  debug:
    msg: "{{ content.content }}"

- name: change dns server
  ansible.windows.win_dns_client:
    adapter_names: Ethernet 2
    dns_servers: "{{ content.content }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: 41ntern.local
    domain_admin_user: USER1@41ntern.local
    domain_admin_password: p@ssw0rd
    domain_ou_path: "OU=COMPUTER,OU=Yuki,DC=41ntern,DC=local"
    state: domain
  register: domain_state
  
- name: Reboot after joining
  win_reboot:
    msg: "Joining domain and Rebooting..."
  when: domain_state.reboot_required

- name: Install IIS
  win_feature:
    name: Web-Server
    include_management_tools: yes
    state: present

- name: Install dotNET 6
  win_package:
    path: https://download.visualstudio.microsoft.com/download/pr/0cb3c095-c4f4-4d55-929b-3b4888a7b5f1/4156664d6bfcb46b63916a8cd43f8305/dotnet-hosting-6.0.13-win.exe
    state: present
    arguments:
    - /install
    - /passive
    - /norestart
    
- name: Copy folder to C:\inetpub\wwwroot\
  ansible.windows.win_copy:
    src: files/top
    dest: C:\inetpub\wwwroot

- name: Create a new application pool in 'Started' state
  win_iis_webapppool:
    name: WebApp
    state: started

- name: Add webapplication on IIS with path = /top
  win_iis_webapplication:
    name: top
    site: Default Web Site
    state: present
    application_pool: WebApp
    physical_path: C:\inetpub\wwwroot\top

- name: Ensure the application pool started
  community.windows.win_iis_webapppool:
    name: top
    state: started