- name: change dns server
  ansible.windows.win_dns_client:
    adapter_names: Ethernet 2
    dns_servers: 172.31.50.237
- name: join domain
  win_domain_membership:
    dns_domain_name: 41ntern.local
    domain_admin_user: USER1@41ntern.local
    domain_admin_password: p@ssw0rd
    domain_ou_path: "OU=COMPUTER,OU=Yuki,DC=41ntern,DC=local"
    state: domain
  register: domain_state
- name: Reboot after joining
  win_reboot:
    msg: "Joining domain and Rebooting..."
  when: domain_state.reboot_required
- name: Install IIS
    win_feature:
      name: Web-Server
      state: present